version: "4.0"

actions:

# delect --dummy-table row when submitting the code (      --dummy-tables dummy-tables )

  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py
      --dummy-tables dummy-tables
      --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz


  generate_histograms:
    run: stata-mp:latest analysis/histograms.do
    needs : [generate_dataset]
    outputs:
      moderately_sensitive:
        Figures1: output/days_since_last_anyvax.svg
        Figures2: output/days_since_last_covax.svg
        Figures3: output/days_since_last_fluvax.svg