version: "5.0"

actions:

# delect --dummy-table row when submitting the code (      --dummy-tables dummy-tables )

  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py
      --dummy-tables dummy-tables
      --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz


  generate_analysis_dataset:
    run: stata-mp:latest analysis/derive_covariates.do
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        log: logs/define_covariates.log
        dataset: output/analytical_cohort.dta
## stata-mp:latest works fine when running generate_analysis_dataset, but when running generate_dataset produces error "not supported"


  generate_histograms:
    run: stata-mp:v2 analysis/histograms.do
    needs : [generate_dataset, generate_analysis_dataset]
    outputs:
      moderately_sensitive:
        Figures1: output/days_since_last_anyvax.svg
        Figures2: output/days_since_last_covax.svg
        Figures3: output/days_since_last_fluvax.svg